name: master branch auto ci process script

on:
  push:
    branches: [ main ]   # 실제 브랜치가 main이면 여기 main으로 바꾸기

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/app/Unid
            git pull origin 
            pm2 kill
            npm i --legacy-peer-deps
            npm run build
            pm2 start dist/main.js
